services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/sonarr:/config
      - ./series:/tv
      - ./downloads:/downloads
      - ./scripts:/scripts
    restart: unless-stopped
    post_start:
      - command: /scripts/set_wg_route.sh
        privileged: true
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/radarr:/config
      - ./movies:/movies
      - ./downloads:/downloads
      - ./scripts:/scripts
    restart: unless-stopped
    post_start:
      - command: /scripts/set_wg_route.sh
        privileged: true
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/prowlarr:/config
      - ./scripts:/scripts
    restart: unless-stopped
    post_start:
      - command: /scripts/set_wg_route.sh
        privileged: true
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/transmission:/config
      - ./downloads:/downloads
      - ./scripts:/scripts
    restart: unless-stopped
    post_start:
      - command: /scripts/set_wg_route.sh
        privileged: true
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/wireguard:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped